name: "Apply git user"
description: "Apply a well-known git user to 'git config user.*'."
branding:
  icon: user-plus
  color: orange

inputs:
  email:
    description: "If 'user' is 'specific', what to set for 'user.email'"
    required: false
    default: ""
  global:
    description: "Whether to set '--global' or not"
    required: false
    default: "false"
  name:
    description: "If 'user' is 'specific', what to set for 'user.name'"
    required: false
    default: ""
  path:
    description: "Relative path under $GITHUB_WORKSPACE to place the repository"
    required: false
    default: ""
  user:
    description: "Which user to apply"
    required: true

runs:
  using: node20
  main: compiled/index.js
