name: "Apply git user"
description: "Apply a well-known git user to 'git config user.*'."
branding:
  icon: "user-plus"
  color: "blue"

inputs:
  global:
    description: "Whether to set '--global' or not"
    required: false
    default: "false"
  path:
    description: "Relative path under $GITHUB_WORKSPACE to place the repository"
    required: false
    default: "."
  user:
    description: "Which user to apply"
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        GLOBAL: ${{ inputs.global }}
        PATH_DIR: ${{ inputs.path }}
        USER: ${{ inputs.user }}
      run: |
        echo "path: $PATH_DIR"
        cd $PATH_DIR
        echo "moved path: $PATH_DIR"

        EMAIL=''
        NAME=''
        user=${USER,,}
        if [ $user = 'actions-user' ]; then
          EMAIL='65916846+actions-user@users.noreply.github.com'
          NAME='actions-user'
        elif [ $user = 'github-actions' ]; then
          EMAIL='41898282+github-actions[bot]@users.noreply.github.com'
          NAME='github-actions[bot]'
        elif [ $user = 'latest-commit' ]; then
          EMAIL="$(git --no-pager log --format=format:'%ae' -n 1)"
          NAME="$(git --no-pager log --format=format:'%an' -n 1)"
        else
          echo "::error::Please set 'user' to either 'actions-user', 'github-actions' or 'latest-commit'."
          exit 1
        fi
        echo "name: $NAME"
        echo "email: $EMAIL"

        FLAG='--local'
        if [ ${GLOBAL,,} = 'true' ]; then
          FLAG='--global'
        fi
        echo "flag: $FLAG"

        git config $FLAG user.email $EMAIL
        git config $FLAG user.name $NAME
