name: 140 Create version pull request

on:
  workflow_dispatch:
    inputs:
      versionMajor:
        description: "バージョン情報: major"
        required: true
        type: string
      versionMinor:
        description: "バージョン情報: minor"
        required: true
        type: string
      versionPatch:
        description: "バージョン情報: patch"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  create-pr:
    if: ${{ github.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Decide version
        id: meta
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION: "${{ inputs.versionMajor }}.${{ inputs.versionMinor }}.${{ inputs.versionPatch }}"
        run: |
          npm version "$VERSION" --no-git-tag-version
          version=$(node -p "require('./package.json').version")
          bash ./.github/scripts/can-release.bash "$version"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - run: npm ci

      - run: npm test

      - run: npm run build

      # https://github.com/actions/checkout/issues/13#issuecomment-724415212
      - name: Set up git user
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Create a pull request
        env:
          BASE: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{ steps.meta.outputs.version }}
        run: |
          branch="feature/$VERSION"
          message="Update $VERSION"

          git switch --create "$branch"
          git add --all compiled/*
          git add package-lock.json
          git add package.json
          git commit --message "$message"
          git push --set-upstream origin "$branch"

          gh pr create --assignee "@me" --base "$BASE" --title "$message" --body ""
